

spring.application.name=WebPortalApp
server.port=${PORT:8080}




#Database Configuration
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}

# Cloudinary configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:demo_cloud}
cloudinary.api-key=${CLOUDINARY_API_KEY:demo_key}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:demo_secret}

#JPA Configuration - Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:none}
spring.jpa.show-sql=true

#Java Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:example@gmail.com}
spring.mail.password=${MAIL_PASSWORD:examplePass}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# JWT configuration
jwt.secret=MySuperSecretKey1234567890
jwt.expiration=86400000
