spring.application.name=MySpringWeb

#database configuration
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url= jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test
spring.datasource.username=3deD3d9mYkr4Mvv.root
spring.datasource.password=yYZOvlUEUVgJZtH2

#JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
